/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.4
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2020 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "LCD_I2C_FUNCS.h"
#include "LCD_I2C_LL_I2C.h"
#include "LCD_I2C_REGS.h"
#include "SDA_aliases.h"
#include "SDA.h"
#include "UART.h"
#include "Opamp.h"
#include "ADC.h"
#include "MQ2_aliases.h"
#include "MQ2.h"
#include "PWM.h"
#include "NivelMax_aliases.h"
#include "NivelMax.h"
#include "Bomba_aliases.h"
#include "Bomba.h"
#include "Cooler_aliases.h"
#include "Cooler.h"
#include "Buzzer_aliases.h"
#include "Buzzer.h"
#include "RXint.h"
#include "SCL_aliases.h"
#include "SCL.h"
#include "I2C.h"
#include "I2C_PVT.h"
#include "Servo_aliases.h"
#include "Servo.h"
#include "Clock.h"
#include "NivelMin_aliases.h"
#include "NivelMin.h"
#include "UART_IntClock.h"
#include "ADC_AMux.h"
#include "ADC_Ext_CP_Clk.h"
#include "ADC_IRQ.h"
#include "ADC_theACLK.h"
#include "core_cm3_psoc5.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"
#include "cy_em_eeprom.h"

/*[]*/

